# Generated by Django 4.2.5 on 2023-09-22 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lesson_1', '0005_alter_category_options_alter_product_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
