# Generated by Django 4.2.4 on 2023-08-19 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Название фирменного знака')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='Url')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Имя категории')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='Url')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225, verbose_name='Наименование')),
                ('slug', models.SlugField(max_length=225, unique=True, verbose_name='Url')),
                ('image', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Изображение')),
                ('description', models.TextField(null=True, verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена')),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Старая цена')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'No'), (1, 'Yes')], default=1, max_length=1, verbose_name='Статус')),
                ('depart', models.CharField(blank=True, max_length=225, verbose_name='Упаковка')),
                ('article', models.CharField(blank=True, max_length=225, verbose_name='Артикуль')),
                ('grade', models.CharField(blank=True, max_length=225, verbose_name='Класс')),
                ('hieght', models.CharField(blank=True, max_length=100, verbose_name='Высота')),
                ('flower_size', models.CharField(blank=True, max_length=225, verbose_name='Размер цветка')),
                ('flowering_period', models.CharField(blank=True, max_length=100, verbose_name='Период')),
                ('landing_place', models.CharField(blank=True, max_length=100, verbose_name='Место посадки')),
                ('frost_resistance', models.CharField(blank=True, max_length=100, verbose_name='Морозостойкость')),
                ('brand_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.brand', verbose_name='Фирменный знак')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flower_shop.category', verbose_name='Категория')),
            ],
        ),
    ]
